export const GROUP_META: Record<string, { name: string; tagline: string }> = {
  chatgpt:          { name: 'ChatGPT',          tagline: 'AI chatbot mạnh nhất của OpenAI' },
  claude:           { name: 'Claude AI',         tagline: 'AI assistant của Anthropic' },
  cursor:           { name: 'Cursor AI',         tagline: 'IDE tích hợp AI cho lập trình viên' },
  perplexity:       { name: 'Perplexity AI',     tagline: 'Công cụ tìm kiếm thông minh' },
  leonardo:         { name: 'Leonardo AI',       tagline: 'Tạo ảnh AI chuyên nghiệp' },
  elevenlabs:       { name: 'ElevenLabs',        tagline: 'Tổng hợp giọng nói AI siêu thực' },
  kling:            { name: 'Kling AI',          tagline: 'Tạo video AI theo văn bản' },
  grok:             { name: 'Grok (xAI)',        tagline: 'AI chatbot của Elon Musk / xAI' },
  krea:             { name: 'KREA AI',           tagline: 'Công cụ sáng tạo hình ảnh AI' },
  veo3:             { name: 'VEO3',              tagline: 'Tạo video AI của Google DeepMind' },
  midjourney:       { name: 'Midjourney',        tagline: 'Tạo ảnh nghệ thuật bằng AI' },
  runway:           { name: 'Runway AI',         tagline: 'Studio video AI sáng tạo' },
  higgsfield:       { name: 'Higgsfield AI',     tagline: 'Tạo video cinematic bằng AI' },
  heygen:           { name: 'HeyGen',            tagline: 'Tạo video avatar AI chuyên nghiệp' },
  hailuo:           { name: 'Hailuo AI',         tagline: 'Tạo video AI của MiniMax' },
  krisp:            { name: 'Krisp',             tagline: 'Lọc tạp âm cuộc họp bằng AI' },
  capcut:           { name: 'CapCut Pro',        tagline: 'Chỉnh sửa video chuyên nghiệp' },
  canva:            { name: 'Canva',             tagline: 'Thiết kế đồ họa trực tuyến' },
  adobe:            { name: 'Adobe',             tagline: 'Bộ công cụ sáng tạo hàng đầu' },
  figma:            { name: 'Figma',             tagline: 'Thiết kế UI/UX cộng tác' },
  lightroom:        { name: 'Lightroom',         tagline: 'Chỉnh sửa ảnh chuyên nghiệp' },
  filmora:          { name: 'Filmora',           tagline: 'Chỉnh sửa video dễ dùng' },
  davinci:          { name: 'DaVinci Resolve',   tagline: 'Phần mềm dựng phim chuyên nghiệp' },
  meitu:            { name: 'Meitu SVIP',        tagline: 'Chỉnh sửa ảnh và làm đẹp' },
  picsart:          { name: 'PicsArt',           tagline: 'Chỉnh sửa ảnh sáng tạo' },
  beautifulai:      { name: 'Beautiful.ai',      tagline: 'Tạo slide thuyết trình AI' },
  veed:             { name: 'Veed.io',           tagline: 'Chỉnh sửa video trực tuyến' },
  sketchup:         { name: 'SketchUp',          tagline: 'Thiết kế 3D kiến trúc' },
  corel:            { name: 'CorelDRAW',         tagline: 'Thiết kế đồ họa vector' },
  autocad:          { name: 'AutoCAD',           tagline: 'Vẽ kỹ thuật CAD chuyên nghiệp' },
  autodesk:         { name: 'Autodesk',          tagline: 'Bộ công cụ kỹ thuật Autodesk' },
  retouch4me:       { name: 'Retouch4me',        tagline: 'Retouching ảnh tự động bằng AI' },
  duolingo:         { name: 'Duolingo',          tagline: 'Học ngoại ngữ vui và hiệu quả' },
  elsa:             { name: 'ELSA Speak',        tagline: 'Luyện phát âm tiếng Anh' },
  grammarly:        { name: 'Grammarly',         tagline: 'Kiểm tra ngữ pháp và viết lách' },
  ejoy:             { name: 'Ejoy English',      tagline: 'Học tiếng Anh qua phim' },
  quillbot:         { name: 'QuillBot',          tagline: 'Viết lại văn bản thông minh' },
  memrise:          { name: 'Memrise',           tagline: 'Học từ vựng theo phương pháp ghi nhớ' },
  hellochinese:     { name: 'HelloChinese',      tagline: 'Học tiếng Trung từ cơ bản' },
  quizlet:          { name: 'Quizlet',           tagline: 'Học và ôn tập qua flashcard' },
  codecademy:       { name: 'Codecademy',        tagline: 'Học lập trình tương tác' },
  studocu:          { name: 'Studocu',           tagline: 'Tài liệu học tập và ghi chú' },
  datacamp:         { name: 'DataCamp',          tagline: 'Học data science và lập trình' },
  coursera:         { name: 'Coursera',          tagline: 'Khóa học từ đại học hàng đầu' },
  skillshare:       { name: 'Skillshare',        tagline: 'Học kỹ năng sáng tạo' },
  udemy:            { name: 'Udemy',             tagline: 'Khóa học online đa dạng' },
  chegg:            { name: 'Chegg',             tagline: 'Hỗ trợ học tập và giải bài tập' },
  kahoot:           { name: 'Kahoot!',           tagline: 'Học qua trò chơi tương tác' },
  wordwall:         { name: 'Wordwall',          tagline: 'Tạo trò chơi học tập' },
  leetcode:         { name: 'LeetCode',          tagline: 'Luyện thuật toán và phỏng vấn' },
  quizizz:          { name: 'Quizizz',           tagline: 'Quiz học tập tương tác' },
  scribd:           { name: 'Scribd',            tagline: 'Thư viện tài liệu và audiobook' },
  busuu:            { name: 'Busuu',             tagline: 'Học ngôn ngữ cùng cộng đồng' },
  netflix:          { name: 'Netflix',           tagline: 'Xem phim và series hàng đầu' },
  youtube:          { name: 'YouTube Premium',   tagline: 'YouTube không quảng cáo + nhạc' },
  spotify:          { name: 'Spotify',           tagline: 'Nghe nhạc không giới hạn' },
  'apple-music':    { name: 'Apple Music',       tagline: 'Nghe nhạc lossless chất lượng cao' },
  tidal:            { name: 'Tidal',             tagline: 'Nhạc Hi-Fi và HiRes Audio' },
  'galaxy-play':    { name: 'Galaxy Play',       tagline: 'Xem phim Việt và quốc tế' },
  tv360:            { name: 'TV360',             tagline: 'Truyền hình OTT của Viettel' },
  vtvcab:           { name: 'VTVCab ON',         tagline: 'Kênh truyền hình VTV và VTVCab' },
  youku:            { name: 'Youku VIP',         tagline: 'Xem phim và nội dung Trung Quốc' },
  'fpt-play':       { name: 'FPT Play',          tagline: 'Xem bóng đá và phim trực tuyến' },
  iqiyi:            { name: 'iQIYI VIP',         tagline: 'Xem phim và series Trung Quốc' },
  vieon:            { name: 'Vieon',             tagline: 'Xem phim Việt - Hàn - HBO' },
  notion:           { name: 'Notion',            tagline: 'Không gian làm việc all-in-one' },
  office365:        { name: 'Office 365',        tagline: 'Bộ ứng dụng Microsoft Office' },
  copilot:          { name: 'Copilot Pro',       tagline: 'AI assistant tích hợp Office' },
  zoom:             { name: 'Zoom Pro',          tagline: 'Họp trực tuyến chuyên nghiệp' },
  gamma:            { name: 'Gamma',             tagline: 'Tạo slide và trang web bằng AI' },
  turnitin:         { name: 'Turnitin',          tagline: 'Kiểm tra đạo văn học thuật' },
  'google-meet':    { name: 'Google Meet',       tagline: 'Họp video miễn phí của Google' },
  tradingview:      { name: 'TradingView',       tagline: 'Phân tích kỹ thuật chứng khoán' },
  camscanner:       { name: 'CamScanner',        tagline: 'Scan tài liệu bằng điện thoại' },
  jetbrains:        { name: 'JetBrains',         tagline: 'IDE chuyên nghiệp cho lập trình' },
  linkedin:         { name: 'LinkedIn',          tagline: 'Mạng xã hội nghề nghiệp' },
  gemini:           { name: 'Gemini',            tagline: 'AI của Google + Google One' },
  'google-one':     { name: 'Google One',        tagline: 'Dung lượng Google Drive gia đình' },
  onedrive:         { name: 'OneDrive',          tagline: 'Lưu trữ đám mây Microsoft' },
  dropbox:          { name: 'Dropbox',           tagline: 'Lưu trữ và chia sẻ file' },
  icloud:           { name: 'iCloud',            tagline: 'Lưu trữ đám mây Apple' },
  nordvpn:          { name: 'NordVPN',           tagline: 'VPN bảo mật hàng đầu thế giới' },
  expressvpn:       { name: 'ExpressVPN',        tagline: 'VPN tốc độ cao đa quốc gia' },
  pia:              { name: 'PIA VPN',           tagline: 'VPN bảo mật Private Internet Access' },
  hma:              { name: 'HMA VPN',           tagline: 'Hide My Ass - VPN đa thiết bị' },
  'hotspot-shield': { name: 'Hotspot Shield',    tagline: 'VPN nhanh và bảo mật' },
  lastpass:         { name: 'LastPass',          tagline: 'Quản lý mật khẩu an toàn' },
  '1password':      { name: '1Password',         tagline: 'Quản lý mật khẩu cao cấp' },
  kaspersky:        { name: 'Kaspersky',         tagline: 'Bảo mật và diệt virus' },
  windows:          { name: 'Windows',           tagline: 'Bản quyền Windows 10/11 Pro' },
  vietmap:          { name: 'Vietmap',           tagline: 'Bản đồ và dẫn đường Việt Nam' },
  chess:            { name: 'Chess.com',         tagline: 'Học và chơi cờ vua trực tuyến' },
  discord:          { name: 'Discord Nitro',     tagline: 'Nâng cấp Discord server và emoji' },
  tinder:           { name: 'Tinder',            tagline: 'Ứng dụng hẹn hò Gold/Platinum' },
  bumble:           { name: 'Bumble',            tagline: 'Kết nối và hẹn hò an toàn' },
}
